### ISSUE TITLE
Quick questions on mini ex 7 by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [Epsilon99/AestheticProgrammingCourse#10]
Wrong link for the image. Btw, where is your reflection on your readme?

**Comment by Epsilon99** [comment]
I havn't uploadet the final product yet, since I'm still trying to get it to work. The combination of DOM libarary and JS syntax really messed with both my head and the product.
   I will have it up before the end of today.

**Comment by Epsilon99** [comment]
It's uploaded now, sorry for the delay.
